# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'Avaliação Gratuita (e4775b4a-21eb-49dc-9ba9-92a85d93ce74)'
    Action: 'Install Extensions'
    WebAppName: 'api7194win'
    ExtensionsList: 'AspNetCoreRuntime.3.1.x64'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Avaliação Gratuita (e4775b4a-21eb-49dc-9ba9-92a85d93ce74)'
    appType: 'webApp'
    WebAppName: 'api7194win'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

- task: UseDotNet@2
  inputs:
        version: '3.1.x'