# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Avaliação Gratuita (e4775b4a-21eb-49dc-9ba9-92a85d93ce74)'
    appType: 'webApp'
    WebAppName: 'api7194win'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.100'